spring:
  application:
    name: transfer-app
  profiles:
    active: local

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetchRegistry: true
    registerWithEureka: true
    enabled: true

